{% set name = "Flask-BasicAuth" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df5ebd489dc0914c224419da059d991eb72988a01cdd4b956d52932ce7d501ff

build:
  noarch: python
  number: 4
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  
  run:
    - python >={{ python_min }}
    - flask

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_basicauth

about:
  home: https://github.com/jpvanhal/flask-basicauth
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'HTTP basic access authentication for Flask.'
  doc_url: https://flask-basicauth.readthedocs.io/en/latest/
  dev_url: https://github.com/jpvanhal/flask-basicauth

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
